Nri story stuff ig
Iamgoofball/Skyrat-tg pull request #1
Opened 2022-11-25 07:06 UTC by Stalkeros2

## About The Pull Request

## How This Contributes To The Skyrat Roleplay Experience

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>
  
</details>

## Changelog

:cl:
add: Added new mechanics or gameplay changes
add: Added more things
del: Removed old things
qol: made something easier to use
balance: rebalanced something
fix: fixed a few things
soundadd: added a new sound thingy
sounddel: removed an old sound thingy
imageadd: added some icons and images
imagedel: deleted some icons and images
spellcheck: fixed a few typos
code: changed some code
refactor: refactored some code
config: changed some config setting
admin: messed with admin stuff
server: something server ops should know
/:cl:

2022-11-25 07:07 UTC, Stalkeros2 commented
It's basically done but i gtg so I don't have time to write the description.

2022-11-26 13:49 UTC, Stalkeros2 commented
Too freaking busy these days so not like I can add a description; merg pls.

2022-11-27 02:52 UTC, Zonespace27 requested changes

2022-11-27 02:52 UTC, Zonespace27 commented on modular_skyrat/modules/stories_system/code/story_datums/very_impactful.dm
> -<<<<<<< HEAD
merge skew

2022-11-27 02:52 UTC, Zonespace27 commented on modular_skyrat/modules/stories_system/code/story_datums/unimpactful.dm
> -<<<<<<< HEAD
merge skew

2022-11-27 02:52 UTC, Zonespace27 commented on modular_skyrat/modules/stories_system/code/story_datums/somewhat_impactful.dm
> -/datum/story_type/somewhat_impactful/paradigm_shift
merge skew

2022-11-27 02:52 UTC, Zonespace27 commented on modular_skyrat/modules/stories_system/code/story_datums/incredibly_impactful.dm
> -<<<<<<< HEAD
merge skew

2022-11-27 02:52 UTC, Zonespace27 commented on modular_skyrat/modules/stories_system/code/story_datums/incredibly_impactful.dm
> ->>>>>>> e3bef5a336e7f5d7c1682f18c0878d79e8acbf4c
merge skew

2022-11-27 02:52 UTC, Zonespace27 commented on modular_skyrat/modules/novaya_ert/code/head.dm
> +	desc = "The radio is as decorative as the hat is. Alt-click to adjust."
have the alt click part be on examine() and have "alt-click" be bold

2022-11-27 02:52 UTC, Zonespace27 commented on modular_skyrat/modules/novaya_ert/code/head.dm
> +	strip_delay = 60
```suggestion
	strip_delay = 6 SECONDS
```

2022-11-27 02:52 UTC, Zonespace27 commented on modular_skyrat/modules/novaya_ert/code/head.dm
> +	to_chat(user, span_notice("You flip the nasal breathing apparatus [src] [helmet_position ? "down" : "up"]."))
balloon alert

2022-11-27 02:52 UTC, Zonespace27 commented on modular_skyrat/modules/novaya_ert/code/suit.dm
> +	strip_delay = 50
```suggestion
	strip_delay = 5 SECONDS
```

2022-11-27 13:54 UTC, Stalkeros2 commented
Gonna work on it somewhere around tomorrow as I'm still fairly busy.

2022-11-28 03:36 UTC, Stalkeros2 commented on modular_skyrat/modules/stories_system/code/story_datums/very_impactful.dm
> -<<<<<<< HEAD
Master branch moment; nothing I can do.

2022-11-29 01:59 UTC, Stalkeros2 commented
Wait a fucking second.

2022-11-29 01:59 UTC, Stalkeros2 commented
Oh my fucking god.

2023-09-15 06:05 UTC, closed without merging